version: '1.0.{build}'

branches:
  only:
    - master

configuration:
  - Release

os: Visual Studio 2015

platform: Any CPU

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
  - git config --global core.autocrlf true
  - ps: $Env:LABEL = "beta1-build" + $Env:APPVEYOR_BUILD_NUMBER

before_build:
  - appveyor-retry dotnet restore

build_script:
  - dotnet build "src\NHasher" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

after_build:
  - dotnet pack "src\NHasher" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts

test_script:
  - dotnet test "test\NHasher.Tests" -c %CONFIGURATION%

artifacts:
  - path: artifacts\**\*.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: YC6Q/kxtfWYsGJbza6xagn8vrxy+o9ejReed0uhLefJSds3PgBzNeXIIJky6JY3f
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true

- provider: GitHub
  tag: Nightly
  release: Current Nightly ({APPVEYOR_REPO_COMMIT_TIMESTAMP})
  description: 'Version: {GIT_VERSION_TAG}'
  auth_token:
    secure: M7aTLuBvKPwYdLI9HQWIzzu/DFg5aZmPse441fhZgGyhdpM779pt8wwOeyRXQyux
  artifact: /.*\.nupkg/
  on:
    branch: master