version: '1.0.{build}'

branches:
  only:
    - master

configuration:
  - Release

os: Visual Studio 2015

platform: Any CPU

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

cache: '%USERPROFILE%\.nuget\packages'

init:
  - git config --global core.autocrlf true
  - ps: $Env:LABEL = "beta1-build" + $Env:APPVEYOR_BUILD_NUMBER

before_build:
  - appveyor-retry dotnet restore

build_script:
  - dotnet build "src\NHasher" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

after_build:
  - dotnet pack "src\NHasher" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts

test_script:
- ps: >-
    $resultsFile = $ENV:APPVEYOR_BUILD_FOLDER + '\results.xml'

    $openCoverConsole = $ENV:USERPROFILE + '\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe'

    $target = '-target:C:\Program Files\dotnet\dotnet.exe'

    $targetArgs = '-targetargs: test ' + $ENV:APPVEYOR_BUILD_FOLDER + '\test\NHasher.Tests -c ' + $ENV:CONFIGURATION

    $filter = '-filter:+[NHasher*]* -[NHasher.Tests]*'

    $output = '-output:' + $resultsFile

    & $openCoverConsole $target $targetArgs '-register:user -returntargetcode' $filter $output '-oldStyle'

    $artifactsFolder = $ENV:APPVEYOR_BUILD_FOLDER + '\artifacts'

    Copy-Item $resultsFile $artifactsFolder

    $ENV:PATH = 'C:\\Python34;C:\\Python34\\Scripts;' + $ENV:PATH

    python -m pip install --upgrade pip

    pip install git+git://github.com/codecov/codecov-python.git

    codecov -f $resultsFile -X gcov

artifacts:
  - path: artifacts\**\*.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: YC6Q/kxtfWYsGJbza6xagn8vrxy+o9ejReed0uhLefJSds3PgBzNeXIIJky6JY3f
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true

- provider: GitHub
  tag: Nightly
  release: Current Nightly
  description: 'Version: {version}'
  auth_token:
    secure: M7aTLuBvKPwYdLI9HQWIzzu/DFg5aZmPse441fhZgGyhdpM779pt8wwOeyRXQyux
  artifact: /.*\.nupkg/
  force_update: true
  on:
    branch: master
