codecov:
  ci:
    - appveyor

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project: yes
    patch: yes
    changes: yes
comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
